"""Initial tables

Revision ID: 69273c25efe8
Revises:
Create Date: 2025-08-15 12:59:48.698652

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '69273c25efe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('markup_percentage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', name='_base_target_uc')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_class', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aggregated_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair_id', sa.Integer(), nullable=True),
    sa.Column('average_buy_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_sell_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('final_buy_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('final_sell_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('markup_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('provider_count', sa.Integer(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['currency_pair_id'], ['currency_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aggregated_rates', schema=None) as batch_op:
        batch_op.create_index('idx_aggregated_pair_time', ['currency_pair_id', 'aggregated_at'], unique=False)

    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('buy_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('sell_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['currency_pair_id'], ['currency_pairs.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.create_index('idx_rates_pair_time', ['currency_pair_id', 'fetched_at'], unique=False)
        batch_op.create_index('idx_rates_provider_time', ['provider_id', 'fetched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.drop_index('idx_rates_provider_time')
        batch_op.drop_index('idx_rates_pair_time')

    op.drop_table('rates')
    with op.batch_alter_table('aggregated_rates', schema=None) as batch_op:
        batch_op.drop_index('idx_aggregated_pair_time')

    op.drop_table('aggregated_rates')
    op.drop_table('users')
    op.drop_table('providers')
    op.drop_table('currency_pairs')
    # ### end Alembic commands ###
